# Use the latest lightweight Python image
FROM dattran453/base_images_arch:v1

# Set the working directory and permissions
USER root

WORKDIR /search_service
RUN pip install --default-timeout=100 --prefer-binary \
    --index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    python-dotenv


# Set PYTHONPATH so the modules can be found
ENV PYTHONPATH="/search_service"

# Expose the application's port
EXPOSE 7001

USER daemon

# Use Gunicorn to run the Flask app with increased timeout
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:7001", "--timeout", "120", "SearchService.wsgi:app"]