FROM dattran453/base-image:v5

USER root
RUN whoami

# Upgrade pip and install Azure logging
RUN python -m pip install gunicorn 

USER daemon

LABEL version="6.0" \
      description="ViFinanceNews Python base image with gunicorn." \
      maintainer="Dat Tran Tien <trantiendat083@gmail.com>"

CMD ["bash"]