apiVersion: v1
kind: ConfigMap
metadata:
  name: vifinancenews-config
  namespace: vifinancenews
data:
  REDIS_HOST: together-ray-37993.upstash.io
  REDIS_PORT: "6379"
  EMAIL_USERNAME: vifinancenewshust@gmail.com
