apiVersion: v1
kind: Service
metadata:
  name: analysis-service
  namespace: vifinancenews
spec:
  selector:
    app: analysis-service
  ports:
    - protocol: TCP
      port: 7003
      targetPort: 7003