apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: vifinancenews
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      port: 6999
      targetPort: 6999