apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: vifinancenews
spec:
  selector:
    app: logging-service
  ports:
    - protocol: TCP
      port: 7004
      targetPort: 7004