FROM dattran453/base_images_arch:v1

# Set the working directory inside the container
USER root 

WORKDIR /analysis_service

RUN pip install --default-timeout=100 --prefer-binary \
    --index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    python-dotenv





# Set PYTHONPATH so the modules can be found
ENV PYTHONPATH="/analysis_service"

# Expose Flask's default port
EXPOSE 7003

USER daemon
# Use Gunicorn to run the Flask app
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:7003", "--timeout", "120", "AnalysisService.wsgi:app"]