# Use the latest lightweight Python image
FROM dattran453/logging_service:v1.0.1

USER root
WORKDIR /logging_service
RUN pip install --default-timeout=100 --prefer-binary \
    --index-url https://pypi.tuna.tsinghua.edu.cn/simple \
    python-dotenv


# Set PYTHONPATH so the module can be found
ENV PYTHONPATH="/logging_service"

# Expose Flask's default port
EXPOSE 7004

USER daemon

# Use a more efficient CMD
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:7004", "--timeout", "120", "LoggingService.app:app"]