apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: vifinancenews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.6
          ports:
            - containerPort: 8000
            - containerPort: 8001
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_DECLARATIVE_CONFIG
              value: /usr/local/kong/kong.yml
            - name: KONG_LOG_LEVEL
              value: debug
          volumeMounts:
            - mountPath: /usr/local/kong/kong.yml
              name: kong-yml
      volumes:
        - name: kong-yml
          hostPath:
            path: /path/to/your/kong.yml  # Update path for your local system