apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: vifinancenews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
        - name: logging-service
          image: dattran453/logging_service:v1.0.0
          ports:
            - containerPort: 7004
          envFrom:
            - configMapRef:
                name: vifinancenews-config
            - secretRef:
                name: vifinancenews-secret