apiVersion: apps/v1
kind: Deployment
metadata:
  name: vifinancenews-redis
  namespace: vifinancenews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vifinancenews-redis
  template:
    metadata:
      labels:
        app: vifinancenews-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: vifinancenews-config
            - secretRef:
                name: vifinancenews-secret