apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: vifinancenews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: dattran453/search_service:v1.0.0
          ports:
            - containerPort: 7001
          envFrom:
            - configMapRef:
                name: vifinancenews-config
            - secretRef:
                name: vifinancenews-secret
            - secretRef:
                name: vittel-s3-credentials
          volumeMounts:
            - mountPath: /app/models/hub
              name: hf-models
      volumes:
          - name: hf-models
            persistentVolumeClaim:
              claimName: hf-models-pvc
            emptyDir: {}