apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: vifinancenews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: dattran453/user_service:v1.0.0
          ports:
            - containerPort: 6998
          envFrom:
            - configMapRef:
                name: vifinancenews-config
            - secretRef:
                name: vifinancenews-secret
